app/cf/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("contacts.urls", namespace="contacts")),
    path("admin/", admin.site.urls),
]

app/contacts/urls.py
from django.urls import path

from . import views

app_name = "contacts"


urlpatterns = [
    path("", views.ContactListView.as_view(), name="contact-list"),
]

app/contacts/models.py
from tabnanny import verbose

from django.db import models


class Agency(models.Model):
    agency = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = "agencies"

    def __str__(self):
        return f"({self.id}) - {self.agency}"


class Role(models.Model):
    role = models.CharField(max_length=255)

    def __str__(self):
        return f"({self.id}) - {self.role}"


class Contact(models.Model):
    contact = models.CharField(max_length=255, unique=True)
    role = models.ForeignKey(Role, on_delete=models.CASCADE, null=True, blank=True)
    agency = models.ForeignKey(Agency, on_delete=models.CASCADE, null=True, blank=True)
    tel = models.CharField(max_length=25)

    def __str__(self):
        return f"{self.contact} - ({self.tel})"

app/contacts/views.py
from django.views.generic import ListView
from django.db.models import Q
from .models import Contact, Role, Agency


class ContactListView(ListView):
    model = Contact
    paginate_by = 10
    
    def get_context_data(self, *args, **kwargs):
        context = super(ContactListView, self).get_context_data(*args, **kwargs)
        context["role_list"] = Role.objects.all()
        return context
    
    def get_queryset(self):
        queryset = Contact.objects.all()
        q = self.request.GET.get("q")
        if q:
            queryset = queryset.filter(
                Q(contact__icontains=q)
                | Q(role__role__icontains=q)
                | Q(agency__agency__icontains=q)
                | Q(tel__icontains=q)
            ).distinct()
        return queryset

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible"
        content="IE=edge">
    <meta name="viewport"
        content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
        crossorigin="anonymous">

    <link rel="preconnect"
        href="https://fonts.googleapis.com">
    <link rel="preconnect"
        href="https://fonts.gstatic.com"
        crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap"
        rel="stylesheet">

    <style>
        html,
        body {
            font-family: 'Montserrat', sans-serif;
        }
    </style>
    <title>

        {% block head_title %}
        Contacts
        {% endblock head_title %}

    </title>
</head>

<body>


    {% block content %}

    {% endblock content %}

    <!-- JavaScript Bundle with Popper -->
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>

</body>

</html>

app/templates/contacts/contact_list.html
{% extends 'base.html' %}


{% block head_title %}
Contacts
{% endblock head_title %}


{% block content %}
<div class="container">
    <h1 class="text-center display-4 mt-3">Contacts</h1>
    <form action="{% url 'contacts:contact-list' %}"
        method="get">
        <input class="form-control form-control-lg rounded-pill my-5 border-dark border-2"
            type="search"
            name="q">
    </form>
    <div class="d-flex justify-content-center">
        <div class="col-lg-3">
            <ul class="list-group">
                {% for object in object_list %}
                <li title="{{object.role}}" class="btn btn-outline-dark mb-2 shadow rounded-pill">
                    {{object}}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock content %}